import type { PaidOffersContent } from '../schema';

export const paidOffers: PaidOffersContent = {
  title: '如果你想走得更深',
  intro: '這份報告能告訴你「現在被讀成什麼」。它不能替你做的，是坐在你對面、看著你的條件說：「換作是你，我會先補這一塊，原因是這個。」那 30 分鐘，我免費給你。',
  primaryLabel: '依你的結果推薦',
  entryLabel: '低風險入口',
  anchorLabel: '完整陪跑',
  earlyBird: '早鳥價',
  allServicesCta: '查看所有服務與定價',
  bookingNote: '不管你選哪個方案，都從一次免費 30 分鐘聊聊開始，先確認你的需求與期待對得上，再決定要不要進行。不適合，我會直接說。',
  guarantee: '滿意保證：第一次合作若你覺得對你沒有幫助，全額退費。風險在我這邊，不在你那邊。',
  creditPolicy: '拆解費用可於 30 天內全額折抵任何衝刺或完整方案。',
  confidentiality: '真人審閱完全保密。未經你書面同意，你的資料絕不會被用作公開案例或見證。',
  bookCta: '為我安排這個',
  recommendedLabel: '多數人從這裡開始',
  freeHeroCta: '領取我的免費 30 分鐘解讀',
  freeReassure: '免費・不推銷・不適合我會直接說',
  freeAgenda:
    '這 30 分鐘會發生什麼：\n・前 10 分鐘：你說現況，我聽。\n・中間 15 分鐘：我直接告訴你，以你的條件，下一步最該先補哪一塊、為什麼。\n・最後 5 分鐘：適合付費服務我會說，不適合我也直接說。\n沒有簡報、沒有逼單。會說真話的人，不需要逼你。',
  paidDivider: '想走得更深、更快？以下是依你結果挑的選項，但隨時都能先從上面的免費聊聊開始。',
  founderLine:
    '我是 Michael。我從四大 ESG 顧問，走到 INSEAD，再走進碳市場第一線，中間最難的，是發現我的頭銜在面試官眼裡根本沒翻譯過來，得自己重新講一次我是誰。這條你正要走的路，我走過，也記得每一個卡住的地方。這通電話，是我本人跟你聊，不是助理、不是表單。',
  replyPrompt: '還不想排時段？直接回信問我一個問題就好。我親手回你，不是機器人。',
  replyCta: '回信問我一個問題',
  replyEmail: 'a0921665857@gmail.com',
  inlineCta: {
    line: '讀到這裡，如果有哪一段讓你想反駁、或想追問「所以我該怎麼做」，直接問我，我親手回，不是機器人。',
    bookCta: '免費 30 分鐘，我唸給你聽',
    replyCta: '回信問一個問題',
    lineCta: '先加 LINE 保存報告',
  },
  offers: {
    intro_call_free: {
      name: '免費 30 分鐘：你這份報告，我親自唸給你聽',
      price: '免費',
      delivery: '一次 30 分鐘線上對談，沒有書面交付。',
      forWhom: '還在觀望、想先確認方向對不對的人。',
      blurb: '這通電話只有一件事：看著你的 MRI 結果，當場告訴你以你現在的條件，最該先補哪一塊、為什麼。沒有簡報、沒有東西要賣你。你會帶走一個清楚的下一步。如果你根本不需要付費服務，我也會直接說。',
    },
    deep_read: {
      name: '深度書面解讀 Deep Read',
      price: 'NT$1,200',
      originalPrice: 'NT$1,500',
      delivery: '非同步書面解讀，48 小時內交付。',
      forWhom: '想要一份更深、可反覆讀的書面判讀，但還不需要真人通話的人。',
      blurb: '把你的 MRI 往下挖一層：點名你最強的三個資產、最該補的一個缺口，附上具體下一步。全部書面，你可以收藏慢讀。',
    },
    consult_60: {
      name: '1 小時診斷諮詢',
      price: 'NT$2,200',
      originalPrice: 'NT$2,800',
      delivery: '一次 60 分鐘線上對談。',
      forWhom: '想要真人一對一、把方向一次談清楚的人。',
      blurb: '比免費聊聊更深、比拆解更輕：一小時把你的定位、目標賽道與下一步談到位，當場給你可執行的方向。',
    },
    teardown_90: {
      name: '90 分鐘故事拆解',
      price: 'NT$2,980',
      originalPrice: 'NT$3,800',
      delivery: '一次 90 分鐘工作對談，72 小時內附上書面備忘錄。',
      forWhom: '任何想快速獲得一份坦率真人判讀的人。',
      blurb: '我們一起逐段看你的真實資料，點名你的主軸，留給你一份備忘錄：最重要的三個修改。',
    },
    cv_linkedin_review: {
      name: 'CV 與 LinkedIn 審閱',
      price: 'NT$2,980',
      originalPrice: 'NT$3,800',
      delivery: '非同步書面審閱，加一次 30 分鐘通話。',
      forWhom: '故事已定，但文件賣低了自己的人。',
      blurb: '逐行檢視你的文件如何承載你的故事：該刪什麼、該浮現什麼，以及篩選者在六秒內實際看到什麼。',
    },
    climate_positioning_sprint: {
      name: '氣候職涯定位衝刺',
      price: 'NT$9,800 起',
      originalPrice: 'NT$12,000 起',
      delivery: '三週內三次工作會議。',
      forWhom: '正在氣候賽道之間抉擇，或需要把技術工作翻譯成商業語言的專業者。',
      blurb: '定下你的目標賽道，點名你的差異化，畫出抵達那裡的兩步棋。用你的證據，不是通用建議。',
    },
    mba_story_sprint: {
      name: '單校 MBA 故事衝刺',
      price: 'NT$12,000 起',
      originalPrice: 'NT$18,000 起',
      priceNote: '可選混合制：較低底價 ＋ 錄取或獲獎學金後再付成功獎金，風險一起分擔。',
      delivery: '四週四次會議，聚焦一所目標學校。',
      forWhom: '目標明確、需要把完整敘事建起來的申請者。',
      blurb: '為一所學校建立定位、essay 方向與面試主幹，全部從你的真實素材出發。協作完成，絕不代寫。',
    },
    mock_interview_pack: {
      name: 'AI＋真人模擬面試組',
      price: 'NT$3,800 起',
      originalPrice: 'NT$4,800 起',
      delivery: '結構化 AI 練習，加一到兩場真人模擬與書面回饋。',
      forWhom: '未來幾個月內就要面試的人。',
      blurb: '在低壓環境無限次練習，再到真實壓力下驗收。回饋針對內容本身，不只是台風。',
    },
    offer_negotiation: {
      name: '綠領 Offer 與薪資談判教練',
      price: 'NT$3,800',
      originalPrice: 'NT$4,800',
      delivery: '一次 60 分鐘策略對談，加一份書面談判準備備忘錄。',
      forWhom: '手上已有或即將拿到 offer，想把條件談到位的人。',
      blurb: '用 INSEAD 談判課的七要素框架，幫你拆解這個 offer 的籌碼、替代方案與對方底線，準備好你的開場、讓步順序與關鍵語句。談的是你的真實情境，不是通用話術。',
    },
    climate_finance_transition: {
      name: '氣候金融／影響力投資轉職衝刺',
      price: 'NT$12,000 起',
      originalPrice: 'NT$15,000 起',
      delivery: '三週三次工作會議，含一份目標角色對位分析。',
      forWhom: '想從 ESG／永續顧問跨到氣候金融、影響力投資或氣候創投的專業者。',
      blurb: '把你的合規與顧問經驗，翻譯成資本市場聽得懂的語言：用永續金融與專案融資的框架，補上你和純金融背景者之間的差距，畫出一條用你既有證據就能走的轉職路徑。',
    },
    full_package: {
      name: '綠色職涯／MBA 完整定位方案',
      price: 'NT$30,000 起',
      originalPrice: 'NT$48,000 起',
      priceNote: '可選混合制：較低底價 ＋ 達成目標（錄取／獲獎學金／拿到 offer）後再付成功獎金。',
      delivery: '八週，端到端。',
      forWhom: '已下定決心、希望整段路有一個人全程負責的專業者。',
      blurb: '以上所有環節，按正確順序串起：定位、故事、文件、面試準備。做到完成，而不只是給建議。',
    },
  },
};
