import type { Locale } from '@/lib/constants';

/**
 * Copy for the /singapore guide page.
 *
 * Stand-alone rather than part of the locale schema for the same reason as
 * content/nav.ts: the guide body itself is a prebuilt zh-TW fragment (see
 * content/singapore-guide/embed.zh-TW.html, generated by the tw2sg pipeline at
 * C:\Users\michael\tw2sg\site — edit the registry/template there and rebuild;
 * never hand-edit the fragment). Only the page chrome strings live here.
 */
export interface SingaporeGuideCopy {
  /** <title> / og title for the page. */
  title: string;
  description: string;
  /**
   * Shown only on the en locale above the zh-TW body: the guide targets
   * Taiwanese readers and is intentionally not translated.
   */
  zhOnlyNote: string;
}

const zh: SingaporeGuideCopy = {
  title: '台灣人赴新加坡工作指南｜官方資訊一次看懂',
  description:
    '從拿 offer 到落地第一年到回台：EP 門檻、落地 30 天、兩邊稅務、台灣健保戶籍、租屋防雷。每條資訊附官方原始連結與抓取日期。',
  zhOnlyNote: '',
};

const en: SingaporeGuideCopy = {
  title: 'Taiwan → Singapore relocation guide (zh-TW)',
  description:
    'Official-steps guide for Taiwanese professionals moving to Singapore: pass thresholds, first 30 days, cross-border tax, NHI and household registry, rental pitfalls. Every claim links to the official source with a capture date.',
  zhOnlyNote:
    'This guide is written in Traditional Chinese for Taiwanese professionals; the rules it covers (Taiwan NHI, household registry, remittance) are Taiwan-specific, so it is intentionally not translated.',
};

export const singaporeGuideCopy: Record<Locale, SingaporeGuideCopy> = { 'zh-TW': zh, en };
