import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { isLocale } from '@/content/locales';
import { singaporeGuideCopy } from '@/content/singaporeGuide';
import type { Locale } from '@/lib/constants';

/**
 * The Taiwan → Singapore relocation guide.
 *
 * The body is a prebuilt, self-contained zh-TW fragment (styles + markup +
 * vanilla JS, all scoped under .tw2sg-root) generated by the tw2sg content
 * pipeline. It ships its own official-source registry with per-card capture
 * dates and a client-side 90-day staleness downgrade, so we inject it verbatim
 * instead of rebuilding 29 cards as React — content updates happen in the
 * pipeline (rebuild + copy), never by hand-editing the fragment.
 */
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const c = singaporeGuideCopy[locale as Locale];
  return { title: c.title, description: c.description };
}

export default async function SingaporeGuidePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const c = singaporeGuideCopy[locale as Locale];
  const fragment = await readFile(
    path.join(process.cwd(), 'content', 'singapore-guide', 'embed.zh-TW.html'),
    'utf8',
  );

  return (
    <main id="main">
      {c.zhOnlyNote ? (
        <p className="mx-auto max-w-2xl px-6 pt-6 text-sm text-ink-soft">{c.zhOnlyNote}</p>
      ) : null}
      {/* suppressHydrationWarning: the fragment's hrefs carry raw `&` (official
          URLs with query strings); the browser serialises them back as `&amp;`,
          so the dev-mode string comparison can never match. React never
          reconciles inside dangerouslySetInnerHTML, so the warning is noise. */}
      <div className="tw2sg-root" suppressHydrationWarning dangerouslySetInnerHTML={{ __html: fragment }} />
    </main>
  );
}
