/**
 * CONSTITUTION LINT — surface collection.
 *
 * Two layers, because copy lives in two places:
 *
 *   Layer A (`copySurfaces`) walks the *imported* copy objects. Precise: a
 *   string here is by definition a string the reader can see, and a code
 *   comment or a `!==` operator can never reach it.
 *
 *   Layer B (`sourceSurfaces`) scans page/component source for hard-coded
 *   literals and JSX text, because app/(site)/[locale]/page.tsx and the result
 *   page still carry a few hundred characters of Chinese written straight into
 *   JSX. Comments and strings are separated by a real scanner, then obvious
 *   code literals (class lists, hrefs, ids) are filtered out.
 *
 * A third source of public text, `content/singapore-guide/embed.*.html`, is
 * generated by the external tw2sg pipeline and must never be hand-edited; it is
 * linted as visible prose only (script, style and comments stripped) so that a
 * regression there is still reported, and the fix goes upstream.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { getContent } from '@/content';
import { costOfLiving } from '@/content/costOfLiving';
import { greenJobs, greenJobsCopy } from '@/content/greenJobs';
import { jdTranslatorCopy } from '@/content/jdTranslator';
import { levelupReports } from '@/content/levelup';
import { marketPulse } from '@/content/marketPulse';
import { mbaRoiCopy } from '@/content/mbaRoi';
import { navCopy } from '@/content/nav';
import { newsletterCopy } from '@/content/newsletter';
import { notFoundCopy } from '@/content/notFound';
import { salaryIndexCopy } from '@/content/salaryIndexCopy';
import { salaryReports } from '@/content/salaryReport';
import { sampleReports } from '@/content/sampleReport';
import { sgOfficialCopy } from '@/content/sgOfficialCopy';
import { singaporeGuideCopy } from '@/content/singaporeGuide';
import judgmentData from '@/content/judgment/data.json';
import { ARCHIVED_OFFER_IDS, PUBLIC_PAID_OFFER_IDS, SERVICE_PRICE } from '@/lib/services';
import { LOCALES } from '@/lib/constants';

export interface Surface {
  /** Dotted path, used as the finding location. */
  path: string;
  text: string;
  /** Selling surfaces are the only ones price-checked. See LintOptions. */
  selling: boolean;
  /** False for the knowledge corpora; see KNOWLEDGE_CORPORA below. */
  marketing: boolean;
}

/* --------------------------- documented exemptions --------------------------- */

/**
 * Every entry is a claim that the strings under it are NOT reader-facing public
 * copy. None of them is "this is too noisy to fix".
 */
export const SKIPPED_SUBTREES: { match: (p: string) => boolean; why: string }[] = [
  {
    match: (p) => ARCHIVED_OFFER_IDS.some((id) => p.includes(`paidOffers.offers.${id}`)),
    why: 'Offers retired by Gate 8. lib/services.ts keeps their copy only so historical DB rows render in admin; no public surface can reach them, and their old price strings (US$39, NT$1,200…) are deliberately frozen history.',
  },
  {
    match: (p) => /\.(url|href|slug|id|token|image|icon|src|utm[A-Za-z]*)$/.test(p),
    why: 'Identifiers and links, not prose. A URL is allowed to contain an offer id or an exclamation mark without addressing the reader.',
  },
  {
    match: (p) => p.startsWith('greenJobs.jobs.') && /\.(org|source|location)$/.test(p),
    why: 'Third-party employer and board names, quoted verbatim. Michael does not author them and must not rewrite them.',
  },
];

/* ------------------------------- generic walker ------------------------------ */

/**
 * Surfaces that teach rather than sell. They quote assurance levels, contract
 * clauses and government figures, so a word like 保證 does real work there; the
 * lint keeps its outcome-promise trigger on them but drops the blanket ban.
 * Everything not listed here is persuasion copy by default — the safe direction
 * for a rule set whose whole purpose is to catch marketing drift.
 */
export const KNOWLEDGE_CORPORA = [
  'judgment',
  'costOfLiving',
  'salaryReports',
  'salaryIndexCopy',
  'sgOfficialCopy',
  'greenJobs',
  'marketPulse',
  'levelupReports',
  'singaporeGuideCopy',
];

function isKnowledge(rootPath: string): boolean {
  const root = rootPath.split(/[.[]/)[0];
  return KNOWLEDGE_CORPORA.includes(root);
}

function walk(node: unknown, prefix: string, out: Surface[], selling: boolean, marketing: boolean) {
  if (SKIPPED_SUBTREES.some((s) => s.match(prefix))) return;
  if (typeof node === 'string') {
    // Evaluated on the full dotted path, not just the module name, so that
    // `zh-TW.results.<category>.offerLine` is price-checked while the rest of
    // the report copy around it is not.
    if (node.trim().length > 0) out.push({ path: prefix, text: node, selling: selling || sellingFor(prefix), marketing });
    return;
  }
  if (Array.isArray(node)) {
    node.forEach((v, i) => walk(v, `${prefix}[${i}]`, out, selling, marketing));
    return;
  }
  if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
      walk(v, prefix ? `${prefix}.${k}` : k, out, selling, marketing);
    }
  }
}

/**
 * Selling surfaces: where Michael's own prices may legitimately appear, and
 * therefore the only places a wrong price is detectable as wrong. Everything
 * else on the site (salary bands, cost-of-living tables, MBA ROI inputs, the
 * judgement corpus) is full of correct money figures that have nothing to do
 * with what he charges.
 */
const SELLING_PATH_RE = /(^|\.)(paidOffers|payment|results\.[a-z_]+\.(offerLine|cta)|landing\.(services|offers|pricing))/;

function sellingFor(rootPath: string): boolean {
  return SELLING_PATH_RE.test(rootPath);
}

/* --------------------------------- layer A ---------------------------------- */

export function copySurfaces(): Surface[] {
  const out: Surface[] = [];

  for (const locale of LOCALES) {
    const c = getContent(locale) as unknown as Record<string, unknown>;
    for (const [section, value] of Object.entries(c)) {
      // The locale tree is the product's own voice end to end: landing, flow,
      // report, offers, emails. All of it is persuasion copy.
      walk(value, `${locale}.${section}`, out, sellingFor(section), true);
    }
  }

  const standalone: Record<string, unknown> = {
    costOfLiving,
    greenJobs,
    greenJobsCopy,
    jdTranslatorCopy,
    levelupReports,
    marketPulse,
    mbaRoiCopy,
    navCopy,
    newsletterCopy,
    notFoundCopy,
    salaryIndexCopy,
    salaryReports,
    sampleReports,
    sgOfficialCopy,
    singaporeGuideCopy,
    judgment: judgmentData,
  };
  for (const [name, value] of Object.entries(standalone)) {
    walk(value, name, out, sellingFor(name), !isKnowledge(name));
  }

  return out;
}

/** The only prices a selling surface may print. */
export function allowedPrices(): string[] {
  const prices = new Set<string>();
  for (const id of PUBLIC_PAID_OFFER_IDS) {
    for (const market of ['tw', 'intl'] as const) prices.add(SERVICE_PRICE[id][market].display);
  }
  return [...prices];
}

/* --------------------------------- layer B ---------------------------------- */

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(HERE, '..', '..');

/**
 * Directories scanned for hard-coded copy, and the ones deliberately left out.
 */
export const SOURCE_ROOTS = ['app', 'components'];
export const SOURCE_EXCLUDED: { match: (rel: string) => boolean; why: string }[] = [
  {
    match: (rel) => rel.startsWith('app/api/'),
    why: 'Route handlers, not rendered pages. Also fenced off this round by an unrelated security workstream — a finding here could not be fixed anyway, so it is reported by the CLI (--include-api) rather than failing the suite.',
  },
  {
    match: (rel) => rel.startsWith('components/admin/') || rel.includes('/admin/'),
    why: 'Admin console. Only Michael sees it; the calm-premium copy rules are about the reader-facing product.',
  },
  {
    match: (rel) => rel.endsWith('.test.ts') || rel.endsWith('.test.tsx'),
    why: 'Tests quote violating strings on purpose.',
  },
];

function listFiles(dir: string, acc: string[] = []): string[] {
  if (!fs.existsSync(dir)) return acc;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (['node_modules', '.next', '.git'].includes(entry.name)) continue;
      listFiles(full, acc);
    } else if (/\.(tsx?|mts)$/.test(entry.name)) acc.push(full);
  }
  return acc;
}

interface Literal {
  text: string;
  line: number;
}

/**
 * Character scanner rather than a regex, because the naive version breaks on
 * three things this codebase is full of: `//` inside a URL string, `'` inside a
 * Chinese sentence, and — the one that actually bit — a backtick inside a
 * regex literal (`components/JudgmentMarkdown.tsx` matches inline code with
 * /`([^`]+)`/). Mistaking that backtick for a template literal swallowed the
 * next forty lines of code and reported its `!==` operators as exclamation
 * marks in the copy. So regex literals are skipped explicitly.
 *
 * Returns string/template literals with comments and regexes removed.
 */
export function extractLiterals(src: string): Literal[] {
  const out: Literal[] = [];
  let i = 0;
  let line = 1;
  const n = src.length;
  const codeOnly: string[] = [];

  /** `/` starts a regex only where a value may begin, never after an operand. */
  const regexCanStart = (): boolean => {
    for (let j = codeOnly.length - 1; j >= 0; j--) {
      const c = codeOnly[j];
      if (/\s/.test(c)) continue;
      if (/[)\]}\w$]/.test(c)) {
        const tail = codeOnly.slice(Math.max(0, j - 8), j + 1).join('');
        return /\b(?:return|typeof|case|in|of|new|delete|void|do|else)$/.test(tail);
      }
      return true;
    }
    return true;
  };

  while (i < n) {
    const ch = src[i];
    const next = src[i + 1];

    if (ch === '\n') {
      line++;
      i++;
      codeOnly.push('\n');
      continue;
    }
    if (ch === '/' && next !== '/' && next !== '*' && regexCanStart()) {
      i++;
      let inClass = false;
      while (i < n) {
        if (src[i] === '\\') {
          i += 2;
          continue;
        }
        if (src[i] === '[') inClass = true;
        else if (src[i] === ']') inClass = false;
        else if (src[i] === '/' && !inClass) {
          i++;
          break;
        } else if (src[i] === '\n') {
          // Not a regex after all (they cannot span lines); bail out safely.
          break;
        }
        i++;
      }
      while (i < n && /[a-z]/.test(src[i])) i++; // flags
      codeOnly.push(' ');
      continue;
    }
    if (ch === '/' && next === '/') {
      while (i < n && src[i] !== '\n') i++;
      continue;
    }
    if (ch === '/' && next === '*') {
      i += 2;
      while (i < n && !(src[i] === '*' && src[i + 1] === '/')) {
        if (src[i] === '\n') line++;
        i++;
      }
      i += 2;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === '`') {
      const quote = ch;
      const startLine = line;
      i++;
      let buf = '';
      while (i < n) {
        if (src[i] === '\\') {
          buf += src[i + 1] ?? '';
          i += 2;
          continue;
        }
        if (src[i] === quote) {
          i++;
          break;
        }
        if (src[i] === '\n') line++;
        // template placeholders are code, not copy
        if (quote === '`' && src[i] === '$' && src[i + 1] === '{') {
          let depth = 1;
          i += 2;
          while (i < n && depth > 0) {
            if (src[i] === '{') depth++;
            else if (src[i] === '}') depth--;
            else if (src[i] === '\n') line++;
            i++;
          }
          continue;
        }
        buf += src[i];
        i++;
      }
      out.push({ text: buf, line: startLine });
      codeOnly.push(' ');
      continue;
    }
    codeOnly.push(ch);
    i++;
  }

  // JSX text nodes: whatever sits between tags once strings and comments are
  // gone. `>` and `<` are also operators and generic brackets, so a candidate is
  // only accepted when it reads as prose — no statement punctuation, no arrow,
  // no comparison. Without this filter `(l) => l.code === x)!;` was reported as
  // an exclamation mark in the reader-facing copy.
  const stripped = codeOnly.join('');
  const jsxText = /(?<=>)([^<>{}]+)(?=<)/g;
  let m: RegExpExecArray | null;
  while ((m = jsxText.exec(stripped)) !== null) {
    const text = m[1].trim();
    if (text.length === 0 || !/[\p{L}]/u.test(text)) continue;
    if (/[;=()[\]|&$\\]|=>|\?\?|\.\.\./.test(text)) continue;
    const lineNo = stripped.slice(0, m.index).split('\n').length;
    out.push({ text, line: lineNo });
  }

  return out;
}

/**
 * Literals that are code wearing quotes: Tailwind class lists, hrefs, keys,
 * date formats. Excluding them is not a copy exemption — they are not copy.
 */
export function looksLikeCode(text: string): boolean {
  const t = text.trim();
  if (t.length === 0) return true;
  if (/^[\w./#@:?&=%+~-]*$/.test(t)) return true; // single token: id, href, class, key
  if (/^https?:\/\//.test(t)) return true;
  const tokens = t.split(/\s+/);
  const codey = tokens.filter((tok) => /^[a-z0-9:[\]/.%_-]+$/.test(tok) && /[-:[\]/]/.test(tok)).length;
  if (tokens.length >= 2 && codey / tokens.length > 0.6) return true; // class list
  return false;
}

export function sourceSurfaces(opts: { includeApi?: boolean } = {}): Surface[] {
  const out: Surface[] = [];
  for (const root of SOURCE_ROOTS) {
    for (const file of listFiles(path.join(REPO_ROOT, root))) {
      const rel = path.relative(REPO_ROOT, file).split(path.sep).join('/');
      const excluded = SOURCE_EXCLUDED.find((e) => e.match(rel));
      if (excluded && !(opts.includeApi && rel.startsWith('app/api/'))) continue;
      const src = fs.readFileSync(file, 'utf8');
      for (const lit of extractLiterals(src)) {
        if (looksLikeCode(lit.text)) continue;
        out.push({
          path: `${rel}:${lit.line}`,
          text: lit.text,
          selling: /services|offer|payment|Cta/i.test(rel),
          // Hard-coded page copy is the product speaking; the two knowledge
          // pages that render corpus data pull their prose from content/.
          marketing: !/judgment|salary|cost-of-living|singapore/i.test(rel),
        });
      }
    }
  }
  return out;
}

/* --------------------------- layer C: html fragments -------------------------- */

export const HTML_FRAGMENTS = [
  'content/singapore-guide/embed.zh-TW.html',
  'content/singapore-guide/embed.en.html',
];

/** Visible prose only: script, style, comments and tags removed. */
export function htmlVisibleText(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/[ \t]+/g, ' ');
}

export function fragmentSurfaces(): Surface[] {
  return HTML_FRAGMENTS.filter((rel) => fs.existsSync(path.join(REPO_ROOT, rel))).map((rel) => ({
    path: rel,
    text: htmlVisibleText(fs.readFileSync(path.join(REPO_ROOT, rel), 'utf8')),
    selling: false,
    // A step-by-step guide to official Singapore procedures, not a pitch.
    marketing: false,
  }));
}

export function allSurfaces(opts: { includeApi?: boolean } = {}): Surface[] {
  return [...copySurfaces(), ...sourceSurfaces(opts), ...fragmentSurfaces()];
}
